apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: tomtest-daily
  name: jenkins-java-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: jenkins-java-demo
  template:
    metadata:
      labels:
        app: jenkins-java-demo
    spec:
      containers:
      - name: jenkins-java-demo
        image: registry.cn-shenzhen.aliyuncs.com/tomtest/jenkins-java-demo:0.0.1
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: registrykey

---
apiVersion: v1
kind: Service
metadata:
  namespace: tomtest-daily
  name: jenkins-java-demo
spec:
  ports:
  - port: 80
    targetPort: 8080
    name: jenkins-java-demo
  selector:
    app: jenkins-java-demo
  type: LoadBalancer
